security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    password_hashers:
        Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface: 'auto'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            logout:
                path: logout
            json_login:
                check_path: /login
    access_control:
        - { path: ^/item, roles: ROLE_USER }
    encoders:
        App\Entity\User:
            algorithm: bcrypt
